CREATE USER mdtp_api;
GRANT USAGE ON SCHEMA public TO mdtp_api;
GRANT INSERT, SELECT, UPDATE ON tbl_grid_items TO mdtp_api;
GRANT ALL ON SEQUENCE tbl_grid_items_id_seq TO mdtp_api;
GRANT INSERT, SELECT, UPDATE ON tbl_base_images TO mdtp_api;
GRANT ALL ON SEQUENCE tbl_base_images_id_seq TO mdtp_api;
GRANT INSERT, SELECT, UPDATE ON tbl_network_updates TO mdtp_api;
GRANT ALL ON SEQUENCE tbl_network_updates_id_seq TO mdtp_api;
GRANT INSERT, SELECT, UPDATE ON tbl_offchain_contents TO mdtp_api;
GRANT ALL ON SEQUENCE tbl_offchain_contents_id_seq TO mdtp_api;
