const hardhat = require("hardhat");

const METADATA_BASE_URI = 'ipfs://QmVTktJb8VSi4AGeuRrv7eeedRxn8Zsh3VU543ZDwDwMbB/';
const DEFAULT_CONTENT_BASE_URI = 'ipfs://QmYeZHGzfUS4R2wfTi1wYW8Cq9eyK4Rea8QQKtG3ERhKfC/'
const COLLECTION_URI = ''
const DEFAULT_TOTAL_MINT_LIMIT = 2000;
const DEFAULT_SINGLE_MINT_LIMIT = 35;
const DEFAULT_USER_MINT_LIMIT = 35;
const DEFAULT_MINT_PRICE = hardhat.ethers.utils.parseEther('0.01');
const DEFAULT_ROYALTY_BASIS_POINTS = 500; // 5%
const ORIGINAL = hardhat.ethers.utils.getAddress('0x1cf33f4c6c4e6391f4d2b445aa3a36639b77dd68');

module.exports = [
  DEFAULT_TOTAL_MINT_LIMIT,
  DEFAULT_SINGLE_MINT_LIMIT,
  DEFAULT_USER_MINT_LIMIT,
  DEFAULT_MINT_PRICE,
  METADATA_BASE_URI,
  DEFAULT_CONTENT_BASE_URI,
  COLLECTION_URI,
  DEFAULT_ROYALTY_BASIS_POINTS,
  ORIGINAL,
];
