
const METADATA_BASE_URI = 'ipfs://QmVTktJb8VSi4AGeuRrv7eeedRxn8Zsh3VU543ZDwDwMbB/';
const DEFAULT_CONTENT_BASE_URI = 'ipfs://QmYeZHGzfUS4R2wfTi1wYW8Cq9eyK4Rea8QQKtG3ERhKfC/'
const DEFAULT_TOTAL_MINT_LIMIT = 1000;
const DEFAULT_SINGLE_MINT_LIMIT = 35;
const DEFAULT_OWNERSHIP_MINT_LIMIT = 35;
const DEFAULT_MINT_PRICE = '10000000000000000'; // 0.01eth
module.exports = [
  DEFAULT_TOTAL_MINT_LIMIT,
  DEFAULT_SINGLE_MINT_LIMIT,
  DEFAULT_OWNERSHIP_MINT_LIMIT,
  DEFAULT_MINT_PRICE,
  METADATA_BASE_URI,
  DEFAULT_CONTENT_BASE_URI,
];
