import json
from typing import Optional

from core.web3.eth_client import EthClientInterface

from mdtp.contract_store import Contract
from mdtp.contract_store import ContractStore


def create_contract_store(ethClient: EthClientInterface, rinkebyEthClient: EthClientInterface, mumbaiEthClient: EthClientInterface, accountAddress: Optional[str] = None, privateKey: Optional[str] = None) -> ContractStore:
    with open('./contract1.json') as contractJsonFile:
        contractJson = json.load(contractJsonFile)['abi']
    with open('./contract2.json') as contractJsonFile:
        contract2Json = json.load(contractJsonFile)['abi']
    with open('./contract3.json') as contractJsonFile:
        contract3Json = json.load(contractJsonFile)['abi']
    with open('./contract4.json') as contractJsonFile:
        contract4Json = json.load(contractJsonFile)['abi']
    with open('./contract5.json') as contractJsonFile:
        contract5Json = json.load(contractJsonFile)['abi']
    with open('./contract6.json') as contractJsonFile:
        contract6Json = json.load(contractJsonFile)['abi']
    with open('./contract7.json') as contractJsonFile:
        contract7Json = json.load(contractJsonFile)['abi']
    with open('./contract8.json') as contractJsonFile:
        contract8Json = json.load(contractJsonFile)['abi']
    contractStore = ContractStore(accountAddress=accountAddress, privateKey=privateKey, contracts=[
        Contract(network='rinkeby', address='0x2744fE5e7776BCA0AF1CDEAF3bA3d1F5cae515d3', sourceNetwork=None, startBlockNumber=0, abi=contractJson, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenURI', setTokenContentUriFieldName='tokenURI', setTokenGroupContentUriMethodName=None, transferTokenMethodName='transferFrom', mintTokenMethodName='mintNFT', mintTokenGroupMethodName=None, mintLimitMethodName=None, transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature=None),
        Contract(network='mumbai', address='0x87084477F7172dfC303A31efd33e9cA6eA8CABCE', sourceNetwork=None, startBlockNumber=0, abi=contractJson, ethClient=mumbaiEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenURI', setTokenContentUriFieldName='tokenURI', setTokenGroupContentUriMethodName=None, transferTokenMethodName='transferFrom', mintTokenMethodName='mintNFT', mintTokenGroupMethodName=None, mintLimitMethodName=None, transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature=None),
        Contract(network='rinkeby2', address='0xeDa9C05612579ff3888C5dCd689566406Df54e01', sourceNetwork=None, startBlockNumber=0, abi=contract2Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='metadataURI', setTokenGroupContentUriMethodName=None, transferTokenMethodName='transferFrom', mintTokenMethodName='mint', mintTokenGroupMethodName=None, mintLimitMethodName=None, transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='rinkeby3', address='0x19559Ac1471e2e4887d63c9363C85BF9f85Fdb67', sourceNetwork=None, startBlockNumber=0, abi=contract3Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='metadataURI', setTokenGroupContentUriMethodName=None, transferTokenMethodName='transferFrom', mintTokenMethodName='mint', mintTokenGroupMethodName=None, mintLimitMethodName=None, transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='rinkeby4', address='0x9B84318C9aC64F564eEc4a703f2dbb742a4D1401', sourceNetwork=None, startBlockNumber=0, abi=contract4Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='metadataURI', setTokenGroupContentUriMethodName=None, transferTokenMethodName='transferFrom', mintTokenMethodName='mint', mintTokenGroupMethodName=None, mintLimitMethodName=None, transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='rinkeby5', address='0xaE70a9accF2E0c16b380C0aa3060E9fBa6718daf', sourceNetwork=None, startBlockNumber=0, abi=contract5Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='contentURI', setTokenGroupContentUriMethodName='setTokenGroupContentURIs', transferTokenMethodName='transferFrom', mintTokenMethodName='mintToken', mintTokenGroupMethodName='mintTokenGroup', mintLimitMethodName='totalMintLimit', transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='rinkeby6', address='0x8f1F643637046c867675Ca101ce28E2763daC1E2', sourceNetwork=None, startBlockNumber=0, abi=contract6Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='contentURI', setTokenGroupContentUriMethodName='setTokenGroupContentURIs', transferTokenMethodName='transferFrom', mintTokenMethodName='mintToken', mintTokenGroupMethodName='mintTokenGroup', mintLimitMethodName='totalMintLimit', transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='mainnet1', address='0x1Cf33F4c6C4E6391F4D2B445aa3a36639b77dd68', sourceNetwork=None, startBlockNumber=13172762, abi=contract7Json, ethClient=ethClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName=None, isTokenSetForMigrationMethodName=None, ownerOfMethodName='ownerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='contentURI', setTokenGroupContentUriMethodName='setTokenGroupContentURIs', transferTokenMethodName='transferFrom', mintTokenMethodName='mintToken', mintTokenGroupMethodName='mintTokenGroup', mintLimitMethodName='totalMintLimit', transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='rinkeby7', address='0x011c7e0cF9BB511B5edF265432582c2505f61677', sourceNetwork='rinkeby6', startBlockNumber=0, abi=contract8Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName='original', isTokenSetForMigrationMethodName='isTokenSetForMigration', ownerOfMethodName='proxiedOwnerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='contentURI', setTokenGroupContentUriMethodName='setTokenGroupContentURIs', transferTokenMethodName='transferFrom', mintTokenMethodName='mintToken', mintTokenGroupMethodName='mintTokenGroup', mintLimitMethodName='totalMintLimit', transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='rinkeby9', address='0x2B45a10bc643aA057da80a2EF5FF63F0C20F5ac0', sourceNetwork='rinkeby6', startBlockNumber=0, abi=contract8Json, ethClient=rinkebyEthClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName='original', isTokenSetForMigrationMethodName='isTokenSetForMigration', ownerOfMethodName='proxiedOwnerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='contentURI', setTokenGroupContentUriMethodName='setTokenGroupContentURIs', transferTokenMethodName='transferFrom', mintTokenMethodName='mintToken', mintTokenGroupMethodName='mintTokenGroup', mintLimitMethodName='totalMintLimit', transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
        Contract(network='mainnet2', address='0x8e720f90014fa4de02627f4a4e217b7e3942d5e8', sourceNetwork='mainnet1', startBlockNumber=14525868, abi=contract8Json, ethClient=ethClient, metadataUriMethodName='tokenURI', tokenContentUriMethodName='tokenContentURI', migrationTargetMethodName='original', isTokenSetForMigrationMethodName='isTokenSetForMigration', ownerOfMethodName='proxiedOwnerOf', totalSupplyMethodName='totalSupply', setTokenContentUriMethodName='setTokenContentURI', setTokenContentUriFieldName='contentURI', setTokenGroupContentUriMethodName='setTokenGroupContentURIs', transferTokenMethodName='transferFrom', mintTokenMethodName='mintToken', mintTokenGroupMethodName='mintTokenGroup', mintLimitMethodName='totalMintLimit', transferMethodSignature='Transfer(address,address,uint256)', updateMethodSignature='TokenContentURIChanged(uint256)'),
    ])
    return contractStore
